python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_1_1.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_1_2.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_1_3.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_1_4.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_1_5.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_1_6.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_1_7.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_1_8.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_1_9.nnet

python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_2_1.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_2_2.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_2_3.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_2_4.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_2_5.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_2_6.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_2_7.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_2_8.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_2_9.nnet

python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_3_1.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_3_2.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_3_3.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_3_4.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_3_5.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_3_6.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_3_7.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_3_8.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_3_9.nnet

python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_4_1.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_4_2.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_4_3.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_4_4.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_4_5.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_4_6.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_4_7.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_4_8.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_4_9.nnet

python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_5_1.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_5_2.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_5_3.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_5_4.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_5_5.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_5_6.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_5_7.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_5_8.nnet
python nnet2onnx.py ~/dnn_verification/resources/acasxu/nnet/ACASXU_experimental_v2a_5_9.nnet